import { Header, Footer, Bottom } from "@/components/common";
import "bootstrap/dist/css/bootstrap.min.css";
import 'font-awesome/css/font-awesome.min.css';
import '../../styles/global.css'


export const metadata = {
  title: "Hotel Management",
  description: "Generated by Samet Koleoglu",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <Bottom />
      </body>
    </html>
  );
}
