# Generated by Django 5.1 on 2024-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_roomimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomimage',
            options={'verbose_name_plural': 'Room Image'},
        ),
        migrations.RemoveField(
            model_name='roomimage',
            name='room_type',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ManyToManyField(to='rooms.roomtype'),
        ),
    ]
