# Generated by Django 5.1 on 2024-08-23 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_alter_roomimage_options_remove_roomimage_room_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomimage',
            name='room_type',
        ),
        migrations.AddField(
            model_name='roomimage',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.roomtype'),
        ),
    ]
